import React, { useState, useCallback, useEffect, useRef } from 'react';
import { 
  Upload, 
  FileText, 
  Loader2, 
  CheckCircle, 
  AlertCircle, 
  Play,
  Presentation,
  Moon,
  Sun,
  Languages,
  Sparkles,
  ArrowRight,
  Zap,
  Highlighter,
  X,
  Eye,
  Download,
  ChevronLeft,
  ChevronRight,
  Maximize2
} from 'lucide-react';
import { parsePdfToImages, generatePdf, generatePptx } from './services/pdfService';
import { processImageWithGemini, checkApiKeySelection, promptForKeySelection } from './services/geminiService';
import { ProcessedPage } from './types';

// ================= Dictionary & Types =================

type Language = 'en' | 'cn';
type Theme = 'dark' | 'light';
type Resolution = '2K' | '4K';

const TRANSLATIONS = {
  en: {
    title: "NotebookLM Fixer",
    subtitle: "PDF Restoration Pro",
    description: "Specifically designed to fix blurry text and artifacts in PDFs generated by NotebookLM. Restore clarity and convert to PPTX.",
    poweredBy: "Powered by Gemini 3.0 Pro",
    selectKey: "Select Billing Project",
    apiKeyActive: "API Key Active",
    billingInfo: "Billing Info",
    uploadTitle: "Upload PDF Document",
    uploadDesc: "Drag and drop your NotebookLM generated PDF. We will reconstruct every page using AI with pixel-perfect clarity.",
    extracting: "Extracting Pages...",
    pages: "Pages",
    start: "Start Restoration",
    exportPdf: "Export PDF",
    exportPptx: "Export PPTX",
    exporting: "Exporting...",
    restored: "Restored",
    failed: "Failed",
    enhancing: "Enhancing...",
    holdToView: "Hold to compare",
    clickToView: "Click to compare",
    page: "Page",
    keyGuideTitle: "API Key Required",
    keyGuideDesc: "To process high-resolution images with Nano Banana Pro, you must select a Google Cloud project associated with billing.",
    connectBtn: "Connect API Key",
    quality: "Quality",
    res2k: "2K",
    res4k: "4K",
    highCost: "Uses more tokens",
    normalCost: "Standard",
    enhancingTo: "Enhancing to",
    allDone: "All pages restored successfully!",
    downloadNow: "Download your files now",
    compareModalTitle: "Image Comparison",
    original: "Original",
    processed: "Restored",
    close: "Close"
  },
  cn: {
    title: "NotebookLM 修复专家",
    subtitle: "PDF 智能超清重绘",
    description: "专为修复 NotebookLM 生成文档中的文字模糊与伪影问题而设计。一键还原清晰画质，支持导出 PDF 与 PPTX。",
    poweredBy: "基于 Gemini 3.0 Pro 构建",
    selectKey: "选择计费项目",
    apiKeyActive: "API 密钥已激活",
    billingInfo: "计费说明",
    uploadTitle: "上传 PDF 文档",
    uploadDesc: "拖放或点击上传您的 NotebookLM PDF。我们将利用 AI 重绘每一页，实现像素级清晰度还原。",
    extracting: "正在提取页面...",
    pages: "页面",
    start: "开始增强",
    exportPdf: "导出 PDF",
    exportPptx: "导出 PPTX",
    exporting: "正在导出...",
    restored: "已修复",
    failed: "失败",
    enhancing: "正在增强...",
    holdToView: "长按对比原图",
    clickToView: "点击查看大图对比",
    page: "页",
    keyGuideTitle: "需配置 API 密钥",
    keyGuideDesc: "为了使用 Nano Banana Pro 处理高分辨率图像，您需要选择一个关联了计费的 Google Cloud 项目。",
    connectBtn: "连接 API 密钥",
    quality: "画质",
    res2k: "2K (快速)",
    res4k: "4K (极致)",
    highCost: "消耗更多 Token",
    normalCost: "标准消耗",
    enhancingTo: "正在提升至",
    allDone: "所有页面修复完成！",
    downloadNow: "立即下载您的文件",
    compareModalTitle: "画质对比",
    original: "原图",
    processed: "修复后",
    close: "关闭"
  }
};

const App: React.FC = () => {
  // Data State
  const [pages, setPages] = useState<ProcessedPage[]>([]);
  
  // Processing State
  const [isProcessing, setIsProcessing] = useState(false);
  const [currentProcessingIndex, setCurrentProcessingIndex] = useState<number>(-1);
  const [isParsing, setIsParsing] = useState(false);
  const [keyAuthorized, setKeyAuthorized] = useState(false);
  const [resolution, setResolution] = useState<Resolution>('2K');

  // Comparison Modal State
  const [viewingIndex, setViewingIndex] = useState<number | null>(null);
  const [isHoldingCompare, setIsHoldingCompare] = useState(false);

  // Export State
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [isExportingPptx, setIsExportingPptx] = useState(false);
  
  // UI State
  const [lang, setLang] = useState<Language>('en');
  const [theme, setTheme] = useState<Theme>('dark');
  const [showCompletionBanner, setShowCompletionBanner] = useState(false);
  
  // Mouse Glow Ref
  const mouseGlowRef = useRef<HTMLDivElement>(null);

  const t = TRANSLATIONS[lang];

  // ================= Effect Hooks =================

  // Mouse Follow Effect
  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (mouseGlowRef.current) {
        // Use transform for performant movement
        // Center the 800x800 div on the cursor
        mouseGlowRef.current.style.transform = `translate(${e.clientX}px, ${e.clientY}px)`;
      }
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  // Sync Language to Body Class
  useEffect(() => {
    document.body.classList.remove('lang-en', 'lang-cn');
    document.body.classList.add(`lang-${lang}`);
  }, [lang]);

  // Sync Theme to HTML Class
  useEffect(() => {
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  // Handle Completion Banner
  useEffect(() => {
    const completed = pages.filter(p => p.status === 'completed').length;
    if (pages.length > 0 && completed === pages.length && !isProcessing) {
      setShowCompletionBanner(true);
    } else {
      setShowCompletionBanner(false);
    }
  }, [pages, isProcessing]);

  // Keyboard Navigation for Modal
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (viewingIndex === null) return;
      
      if (e.key === 'Escape') {
        setViewingIndex(null);
      } else if (e.key === 'ArrowLeft') {
        setViewingIndex(prev => (prev !== null && prev > 0 ? prev - 1 : prev));
      } else if (e.key === 'ArrowRight') {
        setViewingIndex(prev => (prev !== null && prev < pages.length - 1 ? prev + 1 : prev));
      } else if (e.code === 'Space') {
         // Space to compare
         e.preventDefault(); 
         setIsHoldingCompare(true);
      }
    };

    const handleKeyUp = (e: KeyboardEvent) => {
      if (e.code === 'Space') {
        setIsHoldingCompare(false);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    }
  }, [viewingIndex, pages.length]);

  // Handle Key Selection
  const verifyKey = useCallback(async () => {
    try {
      const authorized = await checkApiKeySelection();
      setKeyAuthorized(authorized);
      return authorized;
    } catch (e) {
      console.error("Error checking API key", e);
      return false;
    }
  }, []);

  const handleSelectKey = async () => {
    await promptForKeySelection();
    setKeyAuthorized(true);
  };

  // ================= Theme Toggle Logic =================
  const toggleTheme = (event: React.MouseEvent) => {
    // @ts-ignore
    if (!document.startViewTransition) {
      setTheme(prev => prev === 'dark' ? 'light' : 'dark');
      return;
    }

    const x = event.clientX;
    const y = event.clientY;
    const endRadius = Math.hypot(
      Math.max(x, window.innerWidth - x),
      Math.max(y, window.innerHeight - y)
    );

    // @ts-ignore
    const transition = document.startViewTransition(() => {
      setTheme(prev => prev === 'dark' ? 'light' : 'dark');
    });

    transition.ready.then(() => {
      document.documentElement.animate(
        {
          clipPath: [
            `circle(0px at ${x}px ${y}px)`,
            `circle(${endRadius}px at ${x}px ${y}px)`
          ],
        },
        {
          duration: 500,
          easing: 'ease-in',
          pseudoElement: '::view-transition-new(root)',
        }
      );
    });
  };

  const toggleLanguage = () => {
    setLang(prev => prev === 'en' ? 'cn' : 'en');
  };

  // ================= Export Logic =================
  
  const handleExportPdf = async () => {
    if (isExportingPdf) return;
    setIsExportingPdf(true);
    await new Promise(resolve => setTimeout(resolve, 50));
    
    try {
      generatePdf(pages);
    } catch (error) {
      console.error("Export PDF failed", error);
      alert("Failed to export PDF");
    } finally {
      setIsExportingPdf(false);
    }
  };

  const handleExportPptx = async () => {
    if (isExportingPptx) return;
    setIsExportingPptx(true);
    await new Promise(resolve => setTimeout(resolve, 50));

    try {
      await generatePptx(pages);
    } catch (error) {
      console.error("Export PPTX failed", error);
      alert("Failed to export PPTX");
    } finally {
      setIsExportingPptx(false);
    }
  };

  // ================= Processing Logic =================

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (file.type !== 'application/pdf') {
      alert('Please upload a valid PDF file.');
      return;
    }

    setIsParsing(true);
    try {
      const extractedPages = await parsePdfToImages(file);
      setPages(extractedPages);
    } catch (error) {
      console.error("PDF Parsing Error:", error);
      alert("Failed to parse PDF.");
    } finally {
      setIsParsing(false);
    }
  };

  const startProcessing = async () => {
    if (!keyAuthorized) {
      const success = await verifyKey();
      if (!success) {
        await handleSelectKey();
        return; 
      }
    }

    setIsProcessing(true);
    const newPages = [...pages];

    for (let i = 0; i < newPages.length; i++) {
      if (newPages[i].processedUrl) continue;

      setCurrentProcessingIndex(i);
      newPages[i].status = 'processing';
      newPages[i].resolution = resolution; // Store target resolution
      setPages([...newPages]);

      try {
        const processedImage = await processImageWithGemini(
          newPages[i].originalUrl,
          newPages[i].width,
          newPages[i].height,
          resolution
        );
        newPages[i].processedUrl = processedImage;
        newPages[i].status = 'completed';
      } catch (error) {
        console.error(`Error processing page ${i + 1}`, error);
        newPages[i].status = 'error';
      }
      
      setPages([...newPages]);
    }

    setIsProcessing(false);
    setCurrentProcessingIndex(-1);
  };

  const completedCount = pages.filter(p => p.status === 'completed').length;
  const progress = pages.length > 0 ? (completedCount / pages.length) * 100 : 0;
  const isAllComplete = pages.length > 0 && completedCount === pages.length;

  return (
    <div className="min-h-screen bg-[#f8fafc] dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 flex flex-col font-body transition-colors duration-0 overflow-x-hidden relative">
      
      {/* Background Decor */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        
        {/* Dynamic Mouse Follow Glow */}
        <div 
          ref={mouseGlowRef}
          className="absolute top-0 left-0 w-[800px] h-[800px] -ml-[400px] -mt-[400px] rounded-full blur-[100px] pointer-events-none will-change-transform transition-transform duration-75 ease-out opacity-40 dark:opacity-20 bg-indigo-300 dark:bg-indigo-600/30 mix-blend-multiply dark:mix-blend-screen"
        ></div>

        {/* Existing Static Decor (Kept for depth, but subtle) */}
        <div className="hidden dark:block absolute top-[-15%] left-[10%] w-[50%] h-[500px] bg-indigo-900/20 blur-[120px] rounded-full mix-blend-screen animate-pulse"></div>
        <div className="hidden dark:block absolute bottom-[-10%] right-[5%] w-[45%] h-[500px] bg-purple-900/15 blur-[120px] rounded-full mix-blend-screen"></div>
        <div className="hidden dark:block absolute top-[20%] right-[20%] w-[30%] h-[300px] bg-blue-900/10 blur-[100px] rounded-full mix-blend-screen opacity-50"></div>

        {/* Universal Vignette */}
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-white/80 dark:to-zinc-950/80"></div>
      </div>

      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-zinc-200/50 dark:border-white/5 bg-white/70 dark:bg-zinc-950/70 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="bg-zinc-900 dark:bg-white text-white dark:text-black p-2.5 rounded-xl shadow-lg shadow-indigo-500/20">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-2xl font-heading text-zinc-900 dark:text-white leading-none">
                {t.title}
              </h1>
              <p className="text-xs text-zinc-500 dark:text-zinc-400 font-mono-custom mt-1 tracking-wide">
                {t.subtitle}
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
             {/* Key Status */}
             {!keyAuthorized ? (
                <button 
                  onClick={handleSelectKey}
                  className="hidden md:flex text-xs font-medium bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20 px-3 py-1.5 rounded-full hover:bg-amber-500/20 transition items-center gap-2 animate-pulse"
                >
                  <AlertCircle className="w-3.5 h-3.5" />
                  {t.selectKey}
                </button>
             ) : (
                <span className="hidden md:flex text-xs font-medium bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 px-3 py-1.5 rounded-full items-center gap-2">
                  <CheckCircle className="w-3.5 h-3.5" />
                  {t.apiKeyActive}
                </span>
             )}

            <div className="h-6 w-px bg-zinc-200 dark:bg-white/10 mx-2"></div>

            {/* Toggles */}
            <button onClick={toggleLanguage} className="p-2 rounded-full hover:bg-zinc-100 dark:hover:bg-white/5 text-zinc-600 dark:text-zinc-400 border border-transparent hover:border-zinc-200 dark:hover:border-white/10">
              <div className="flex items-center gap-1.5 text-sm font-medium">
                <Languages className="w-4 h-4" />
                <span className="font-mono-custom">{lang === 'en' ? 'CN' : 'EN'}</span>
              </div>
            </button>

            <button onClick={toggleTheme} className="p-2 rounded-full hover:bg-zinc-100 dark:hover:bg-white/5 text-zinc-600 dark:text-zinc-400 border border-transparent hover:border-zinc-200 dark:hover:border-white/10">
              {theme === 'dark' ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative z-10 flex-1 max-w-5xl mx-auto px-6 py-12 w-full flex flex-col gap-8">
        
        {/* Upload State */}
        {pages.length === 0 && (
          <div className="flex flex-col items-center justify-center flex-1 animate-in fade-in zoom-in duration-500">
            <div className="text-center mb-10 max-w-2xl">
               <h2 className="text-4xl md:text-5xl font-heading mb-6 text-zinc-900 dark:text-white">
                 {lang === 'en' ? 'Reimagine your ' : '重塑您的 '}
                 <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 to-purple-500">
                   NotebookLM
                 </span>
                 {lang === 'en' ? ' documents.' : ' 文档。'}
               </h2>
               <p className="text-lg text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-xl mx-auto">
                 {t.description}
               </p>
            </div>

            {!keyAuthorized && (
              <div className="w-full max-w-xl mb-8 p-4 bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-500/20 rounded-2xl flex items-start gap-4 shadow-sm animate-in slide-in-from-bottom-2">
                <div className="p-2 bg-amber-100 dark:bg-amber-500/20 text-amber-600 dark:text-amber-400 rounded-lg shrink-0">
                  <Zap className="w-5 h-5" />
                </div>
                <div className="flex-1">
                  <h4 className="text-sm font-bold text-amber-900 dark:text-amber-100 mb-1">{t.keyGuideTitle}</h4>
                  <p className="text-xs text-amber-700 dark:text-amber-300 leading-relaxed mb-3">
                    {t.keyGuideDesc}
                  </p>
                  <button 
                    onClick={handleSelectKey}
                    className="text-xs font-semibold bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
                  >
                    {t.connectBtn} <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
              </div>
            )}

            <div className="w-full max-w-xl">
              <input 
                type="file" 
                accept="application/pdf"
                onChange={handleFileUpload}
                className="hidden"
                id="pdf-upload"
                disabled={isParsing}
              />
              <label 
                htmlFor="pdf-upload" 
                className={`group relative flex flex-col items-center justify-center p-16 w-full border border-dashed rounded-3xl transition-all cursor-pointer backdrop-blur-sm shadow-sm overflow-hidden ${
                  keyAuthorized 
                    ? "border-zinc-300 dark:border-white/10 bg-white/50 dark:bg-white/5 hover:bg-white/80 dark:hover:bg-white/10 hover:border-indigo-500/50 dark:hover:border-indigo-400/50" 
                    : "border-zinc-200 dark:border-white/5 bg-zinc-50 dark:bg-white/5 opacity-80"
                }`}
              >
                {keyAuthorized && (
                  <div className="absolute inset-0 bg-gradient-to-tr from-indigo-500/0 via-indigo-500/0 to-indigo-500/0 group-hover:from-indigo-500/5 group-hover:to-purple-500/5 transition-all duration-500"></div>
                )}
                
                {isParsing ? (
                  <Loader2 className="w-12 h-12 text-indigo-500 animate-spin mb-6" />
                ) : (
                  <div className="relative">
                    <div className="absolute -inset-4 bg-indigo-500/20 rounded-full blur-xl opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <Upload className="relative w-12 h-12 text-zinc-400 group-hover:text-indigo-500 transition-colors mb-6 duration-300" />
                  </div>
                )}
                
                <h3 className="text-xl font-medium text-zinc-900 dark:text-white mb-2 relative z-10">
                  {isParsing ? t.extracting : t.uploadTitle}
                </h3>
                <p className="text-sm text-zinc-500 dark:text-zinc-400 text-center relative z-10 max-w-xs">
                  {t.uploadDesc}
                </p>
              </label>
            </div>
          </div>
        )}

        {/* Working State: Action Bar */}
        {pages.length > 0 && (
          <div className="sticky top-24 z-40 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl border border-zinc-200/50 dark:border-white/10 rounded-2xl p-4 shadow-2xl shadow-black/5 dark:shadow-black/20 flex flex-wrap items-center justify-between gap-6 animate-in slide-in-from-bottom-4 duration-500">
             
             {/* Progress Info */}
             <div className="flex items-center gap-6 flex-1 min-w-[200px]">
                <div className="flex flex-col">
                  <span className="text-xs font-mono-custom text-zinc-500 uppercase tracking-wider">{t.pages}</span>
                  <div className="flex items-baseline gap-1">
                    <span className="text-2xl font-heading text-zinc-900 dark:text-white">{completedCount}</span>
                    <span className="text-zinc-400">/ {pages.length}</span>
                  </div>
                </div>
                
                <div className="flex-1 h-1.5 bg-zinc-200 dark:bg-white/10 rounded-full overflow-hidden relative">
                  <div 
                    className={`h-full transition-all duration-500 ease-out relative ${
                      isAllComplete 
                      ? 'bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)]' 
                      : 'bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)]'
                    }`}
                    style={{ width: `${progress}%` }}
                  >
                     {!isAllComplete && <div className="absolute right-0 top-0 bottom-0 w-2 bg-white/50 animate-pulse"></div>}
                  </div>
                </div>
             </div>

             {/* Controls */}
             <div className="flex items-center gap-3">
               
               {/* Resolution Switcher (Only show if not started or processing) */}
               {(!isProcessing && completedCount < pages.length) && (
                 <div className="hidden sm:flex items-center bg-zinc-100 dark:bg-white/5 p-1 rounded-xl border border-zinc-200 dark:border-white/10 mr-2">
                    <button 
                      onClick={() => setResolution('2K')}
                      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                        resolution === '2K' 
                        ? 'bg-white dark:bg-zinc-800 shadow-sm text-zinc-900 dark:text-white' 
                        : 'text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200'
                      }`}
                    >
                      {t.res2k}
                    </button>
                    <div className="w-px h-4 bg-zinc-200 dark:bg-white/10 mx-1"></div>
                    <button 
                      onClick={() => setResolution('4K')}
                      className={`group/4k relative px-3 py-1.5 rounded-lg text-xs font-medium transition-all flex items-center gap-1.5 ${
                        resolution === '4K' 
                        ? 'bg-indigo-500 text-white shadow-sm shadow-indigo-500/30' 
                        : 'text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200'
                      }`}
                    >
                      {t.res4k}
                      {resolution === '4K' && <Zap className="w-3 h-3 fill-current animate-pulse" />}
                      
                      {/* Tooltip */}
                      {resolution === '4K' && (
                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 px-3 py-1.5 bg-zinc-900 dark:bg-zinc-800 text-white text-[10px] rounded-lg whitespace-nowrap opacity-0 group-hover/4k:opacity-100 transition-opacity pointer-events-none shadow-xl border border-white/10 z-50">
                          {t.highCost}
                          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-1 border-4 border-transparent border-t-zinc-900 dark:border-t-zinc-800"></div>
                        </div>
                      )}
                    </button>
                 </div>
               )}

               {/* Start Button */}
               {!isProcessing && completedCount < pages.length && (
                 <button 
                  onClick={startProcessing}
                  className={`group relative flex items-center gap-2 pl-5 pr-6 py-2.5 rounded-xl font-medium transition-all transform active:scale-95 overflow-hidden ${
                    keyAuthorized 
                      ? "bg-zinc-900 dark:bg-white text-white dark:text-black hover:shadow-lg hover:shadow-indigo-500/20" 
                      : "bg-zinc-100 dark:bg-white/5 text-zinc-400 cursor-not-allowed border border-zinc-200 dark:border-white/5"
                  }`}
                  disabled={!keyAuthorized}
                > 
                   {keyAuthorized && <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>}
                   {isProcessing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-current" />}
                   <span>{t.start}</span>
                 </button>
               )}

               <div className="h-8 w-px bg-zinc-200 dark:bg-white/10 mx-2"></div>

               <div className="flex gap-2">
                 <button 
                  onClick={handleExportPdf}
                  disabled={completedCount === 0 || isProcessing || isExportingPdf}
                  className={`relative p-2.5 rounded-xl border transition-all group overflow-hidden ${
                    isExportingPdf 
                      ? "bg-indigo-50 dark:bg-indigo-500/10 border-indigo-200 dark:border-indigo-500/30 text-indigo-600 dark:text-indigo-400 cursor-wait"
                      : "bg-white dark:bg-white/5 border-zinc-200 dark:border-white/10 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-white/10 hover:border-zinc-300 dark:hover:border-white/20 disabled:opacity-50 disabled:cursor-not-allowed"
                  }`}
                  title={t.exportPdf}
                 >
                   {isExportingPdf ? (
                     <Loader2 className="w-5 h-5 animate-spin" />
                   ) : (
                     <FileText className="w-5 h-5 group-hover:scale-110 transition-transform" />
                   )}
                 </button>

                 <button 
                  onClick={handleExportPptx}
                  disabled={completedCount === 0 || isProcessing || isExportingPptx}
                  className={`relative p-2.5 rounded-xl border transition-all group overflow-hidden ${
                    isExportingPptx 
                      ? "bg-orange-50 dark:bg-orange-500/10 border-orange-200 dark:border-orange-500/30 text-orange-600 dark:text-orange-400 cursor-wait"
                      : "bg-white dark:bg-white/5 border-zinc-200 dark:border-white/10 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-white/10 hover:border-zinc-300 dark:hover:border-white/20 disabled:opacity-50 disabled:cursor-not-allowed"
                  }`}
                  title={t.exportPptx}
                 >
                   {isExportingPptx ? (
                     <Loader2 className="w-5 h-5 animate-spin" />
                   ) : (
                     <Presentation className="w-5 h-5 group-hover:scale-110 transition-transform" />
                   )}
                 </button>
               </div>
             </div>
          </div>
        )}

        {/* Grid View */}
        {pages.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 pb-20">
            {pages.map((page, idx) => (
              <div 
                key={idx} 
                className={`relative group bg-white dark:bg-zinc-900 border rounded-2xl overflow-hidden transition-all duration-500 hover:shadow-2xl hover:shadow-black/10 dark:hover:shadow-black/20 ${
                  currentProcessingIndex === idx 
                    ? 'border-indigo-500 shadow-[0_0_30px_rgba(99,102,241,0.15)] ring-1 ring-indigo-500/50 scale-[1.02] z-10' 
                    : page.status === 'completed' 
                      ? 'border-emerald-500/30 dark:border-emerald-500/20' 
                      : 'border-zinc-200 dark:border-white/5'
                }`}
              >
                {/* Status Badges (Top Right) */}
                <div className="absolute top-4 right-4 z-20 flex flex-col gap-2 items-end">
                  {page.status === 'completed' && (
                     <>
                      <span className="bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 text-xs font-medium px-2.5 py-1 rounded-full border border-emerald-500/20 flex items-center gap-1.5 backdrop-blur-md shadow-lg animate-in fade-in zoom-in">
                        <CheckCircle className="w-3.5 h-3.5" /> {t.restored}
                      </span>
                      {/* Resolution Badge */}
                      {page.resolution && (
                         <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full backdrop-blur-md shadow-lg border animate-in fade-in zoom-in delay-100 ${
                           page.resolution === '4K' 
                             ? 'bg-amber-500/20 text-amber-600 dark:text-amber-400 border-amber-500/30' 
                             : 'bg-zinc-500/20 text-zinc-600 dark:text-zinc-400 border-zinc-500/30'
                         }`}>
                           {page.resolution}
                         </span>
                      )}
                     </>
                  )}
                  {page.status === 'error' && (
                     <span className="bg-red-500/20 text-red-600 dark:text-red-400 text-xs font-medium px-2.5 py-1 rounded-full border border-red-500/20 flex items-center gap-1.5 backdrop-blur-md shadow-lg">
                       <AlertCircle className="w-3.5 h-3.5" /> {t.failed}
                     </span>
                  )}
                </div>

                {/* Processing Overlay */}
                {page.status === 'processing' && (
                  <div className="absolute inset-0 z-30 bg-zinc-900/40 backdrop-blur-[3px] flex flex-col items-center justify-center">
                    <div className="relative">
                      <div className="absolute inset-0 bg-indigo-500 rounded-full blur-xl opacity-20 animate-pulse"></div>
                      <Loader2 className="relative w-10 h-10 text-white animate-spin" />
                    </div>
                    <span className="text-white/90 font-medium mt-3 tracking-wide text-sm">{t.enhancing}</span>
                    <span className="text-white/60 text-xs mt-1 font-mono-custom">
                       {t.enhancingTo} {page.resolution || resolution}
                    </span>
                  </div>
                )}

                {/* Clickable Area for Comparison */}
                <div 
                  onClick={() => page.status === 'completed' && setViewingIndex(idx)}
                  className={`aspect-[3/4] relative w-full bg-zinc-100 dark:bg-zinc-950 p-2 ${page.status === 'completed' ? 'cursor-zoom-in' : ''}`}
                >
                  {page.processedUrl ? (
                     <div className="w-full h-full relative">
                        <img 
                          src={page.processedUrl} 
                          alt="Enhanced"
                          className="w-full h-full object-contain rounded-lg shadow-inner bg-white dark:bg-zinc-900"
                        />
                        {/* Hover Prompt */}
                        <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/20 rounded-lg pointer-events-none">
                            <div className="px-4 py-2 bg-black/80 backdrop-blur-md rounded-full text-xs text-white border border-white/10 shadow-xl flex items-center gap-2">
                               <Maximize2 className="w-3 h-3" />
                               {t.clickToView}
                            </div>
                        </div>
                     </div>
                  ) : (
                    <img 
                      src={page.originalUrl} 
                      alt="Original"
                      className="w-full h-full object-contain rounded-lg opacity-60 grayscale-[20%] mix-blend-multiply dark:mix-blend-normal"
                    />
                  )}
                </div>
                
                {/* Page Number */}
                <div className="absolute bottom-2 left-2 text-[10px] font-mono-custom text-zinc-400 px-2 py-1 bg-white/50 dark:bg-black/50 backdrop-blur-sm rounded">
                   {t.page} {page.pageIndex}
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* Completion Banner (Fixed Bottom) */}
      {showCompletionBanner && (
        <div className="fixed bottom-0 left-0 right-0 z-50 p-6 flex justify-center pointer-events-none">
           <div className="pointer-events-auto max-w-2xl w-full bg-white dark:bg-zinc-900 border border-emerald-500/30 shadow-2xl shadow-emerald-500/20 rounded-2xl p-4 md:p-5 flex flex-col md:flex-row items-center justify-between gap-4 animate-in slide-in-from-bottom-10 fade-in duration-500">
              <div className="flex items-center gap-4 text-center md:text-left">
                 <div className="p-3 bg-emerald-500/10 rounded-full text-emerald-500 shrink-0">
                    <Sparkles className="w-6 h-6 fill-current" />
                 </div>
                 <div>
                    <h3 className="text-base font-bold text-zinc-900 dark:text-white">{t.allDone}</h3>
                    <p className="text-sm text-zinc-500 dark:text-zinc-400">{t.downloadNow}</p>
                 </div>
              </div>
              <div className="flex items-center gap-3 w-full md:w-auto">
                 {/* PDF Button */}
                 <button 
                   onClick={handleExportPdf}
                   disabled={isExportingPdf}
                   className={`flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border font-medium transition-all ${
                     isExportingPdf
                     ? "bg-indigo-50 dark:bg-indigo-500/10 border-indigo-200 dark:border-indigo-500/30 text-indigo-600 dark:text-indigo-400 cursor-wait"
                     : "bg-white dark:bg-white/5 border-zinc-200 dark:border-white/10 text-zinc-700 dark:text-zinc-200 hover:bg-zinc-50 dark:hover:bg-white/10 hover:border-zinc-300 dark:hover:border-white/20 shadow-sm"
                   }`}
                 >
                    {isExportingPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                    <span>PDF</span>
                 </button>

                 {/* PPTX Button */}
                 <button 
                   onClick={handleExportPptx}
                   disabled={isExportingPptx}
                   className={`flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border font-medium transition-all ${
                     isExportingPptx
                     ? "bg-orange-50 dark:bg-orange-500/10 border-orange-200 dark:border-orange-500/30 text-orange-600 dark:text-orange-400 cursor-wait"
                     : "bg-white dark:bg-white/5 border-zinc-200 dark:border-white/10 text-zinc-700 dark:text-zinc-200 hover:bg-zinc-50 dark:hover:bg-white/10 hover:border-zinc-300 dark:hover:border-white/20 shadow-sm"
                   }`}
                 >
                    {isExportingPptx ? <Loader2 className="w-4 h-4 animate-spin" /> : <Presentation className="w-4 h-4" />}
                    <span>PPTX</span>
                 </button>

                 <button 
                    onClick={() => setShowCompletionBanner(false)}
                    className="p-2.5 text-zinc-400 hover:text-zinc-500 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg transition-colors ml-1"
                 >
                    <X className="w-5 h-5" />
                 </button>
              </div>
           </div>
        </div>
      )}

      {/* Full Screen Comparison Modal */}
      {viewingIndex !== null && pages[viewingIndex] && (
        <div className="fixed inset-0 z-[100] bg-zinc-950/95 backdrop-blur-md flex flex-col animate-in fade-in duration-200">
           {/* Modal Header */}
           <div className="flex items-center justify-between p-4 md:p-6 text-white/80">
              <div className="flex items-center gap-4">
                 <h3 className="text-lg font-heading">{t.compareModalTitle}</h3>
                 <span className="text-xs font-mono-custom opacity-50 border border-white/20 px-2 py-0.5 rounded">
                    {t.page} {pages[viewingIndex].pageIndex}
                 </span>
                 {pages[viewingIndex].resolution && (
                   <span className="text-xs font-bold text-amber-400 border border-amber-500/30 px-2 py-0.5 rounded bg-amber-500/10">
                      {pages[viewingIndex].resolution}
                   </span>
                 )}
              </div>
              <button 
                onClick={() => setViewingIndex(null)}
                className="p-2 hover:bg-white/10 rounded-full transition-colors"
              >
                <X className="w-6 h-6" />
              </button>
           </div>

           {/* Modal Content */}
           <div className="flex-1 relative flex items-center justify-center p-4 overflow-hidden select-none">
              
              {/* Navigation Arrows */}
              <button 
                 onClick={(e) => { e.stopPropagation(); setViewingIndex(prev => (prev !== null && prev > 0 ? prev - 1 : prev)) }}
                 className={`absolute left-4 p-3 bg-black/50 hover:bg-white/10 text-white rounded-full backdrop-blur-sm z-20 transition-opacity ${viewingIndex === 0 ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
              >
                 <ChevronLeft className="w-6 h-6" />
              </button>
              
              <button 
                 onClick={(e) => { e.stopPropagation(); setViewingIndex(prev => (prev !== null && prev < pages.length - 1 ? prev + 1 : prev)) }}
                 className={`absolute right-4 p-3 bg-black/50 hover:bg-white/10 text-white rounded-full backdrop-blur-sm z-20 transition-opacity ${viewingIndex === pages.length - 1 ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
              >
                 <ChevronRight className="w-6 h-6" />
              </button>

              {/* Image Display */}
              <div 
                className="relative max-w-full max-h-full aspect-[3/4] shadow-2xl"
                onMouseDown={() => setIsHoldingCompare(true)}
                onMouseUp={() => setIsHoldingCompare(false)}
                onMouseLeave={() => setIsHoldingCompare(false)}
                onTouchStart={() => setIsHoldingCompare(true)}
                onTouchEnd={() => setIsHoldingCompare(false)}
              >
                 {/* Original Image (Shows when holding) */}
                 <img 
                    src={pages[viewingIndex].originalUrl} 
                    className={`max-w-full max-h-[80vh] object-contain rounded-lg transition-opacity duration-100 absolute inset-0 z-10 ${isHoldingCompare ? 'opacity-100' : 'opacity-0'}`}
                    alt="Original"
                 />
                 
                 {/* Processed Image (Shows by default) */}
                 <img 
                    src={pages[viewingIndex].processedUrl || ''} 
                    className="max-w-full max-h-[80vh] object-contain rounded-lg relative z-0"
                    alt="Processed"
                 />

                 {/* Label Indicator Overlay */}
                 <div className="absolute top-4 left-1/2 -translate-x-1/2 bg-black/60 backdrop-blur-md px-4 py-2 rounded-full text-white text-sm font-medium border border-white/10 pointer-events-none z-20">
                    {isHoldingCompare ? t.original : t.processed}
                 </div>
              </div>
           </div>

           {/* Modal Footer (Instructions) */}
           <div className="p-6 text-center">
              <div 
                className={`inline-flex items-center gap-3 px-6 py-3 rounded-full border transition-all select-none cursor-pointer active:scale-95 ${isHoldingCompare ? 'bg-white text-black border-white' : 'bg-white/10 text-white border-white/10 hover:bg-white/20'}`}
                onMouseDown={() => setIsHoldingCompare(true)}
                onMouseUp={() => setIsHoldingCompare(false)}
                onMouseLeave={() => setIsHoldingCompare(false)}
                onTouchStart={() => setIsHoldingCompare(true)}
                onTouchEnd={() => setIsHoldingCompare(false)}
              >
                 <Eye className="w-5 h-5" />
                 <span className="font-medium">{t.holdToView}</span>
              </div>
              <p className="mt-4 text-xs text-white/40 font-mono-custom hidden md:block">
                 Press Spacebar to compare • Arrow keys to navigate
              </p>
           </div>
        </div>
      )}
    </div>
  );
};

export default App;